### ISSUE TITLE
Documented list of api interfaces by language?

### ISSUE THREAD

**Issue by Arinerron** [towerofnix/scratch-api-unofficial-docs#15]
Hello,
    This is a question, not an issue. Will there be in this repository a list with the different API interfaces by language? If this is planned, I'll comment the list below of API interfaces I know of. If not, Just close this issue :)
Thanks!

**Comment by liam4** [comment]
Do you mean the modules that allow you to easily do things with the API, like scratch-api?

**Comment by GarethPW** [comment]
@Arinerron Might be useful if you post this information anyway so I can post it on the wiki page.

**Comment by Arinerron** [comment]
@GarethPW 
https://github.com/trumank/scratch-api - NodeJS
https://github.com/Dylan5797/ScratchAPI - Python

...and soon to be one more when mine is done :)
