### ISSUE TITLE
Add project comment APIs

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/scratch-api-unofficial-docs#29]
See https://github.com/LLK/scratch-www/pull/1997.

**Comment by towerofnix** [comment]
Looks like it's changed: https://github.com/LLK/scratch-www/pull/2228 - although this isn't reflected in the current API.

**Comment by RedGuy12** [comment]
What URL is this?

**Comment by towerofnix** [comment]
Updated again in https://github.com/LLK/scratch-www/pull/3069! (This is the current `git blame` for the relevant code lines.)

**Comment by micahlt** [comment]
My word Scratch Team - make up your mind!  All right, I'll try to doc this when I get a chance.

**Comment by towerofnix** [comment]
@micahlt I self-assigned this one - I'll be working on it myself, thanks :)

Since we'll be having more than one working on the codebase, I'd appreciate if you ask before getting started with a PR. That way we can keep everything organized and not waste anyone's work! :shipit:

**Comment by towerofnix** [comment]
To-dos (closing the original issues to keep track of them all here):

- [x] Get top-level comments (updated URL/doc file)
- [x] Get replies to top-level comment (updated URL/doc file)
- [x] Get individual comment
- [ ] Write new comment (top-level or reply)
- [ ] Delete existing comment

Also admin endpoints, though these are lower priority, so I'm leaving them tracked in #40.

See also #46, because when studios are ported, there will probably be a *lot* of very similar API information shared between the two, and we might be able to restructure the docs to better better account for that!
