### ISSUE TITLE
followers count

### ISSUE THREAD

**Issue by RedGuy12** [towerofnix/scratch-api-unofficial-docs#56]
is there any way to get the total follower count of a scratcher?

**Comment by towerofnix** [comment]
Not without finding the last page containing followers and [doing the math](https://scratch.mit.edu/users/_nix/#comments-73748739) to calculate it, no. Presumably there will be in the future, once user profile pages are migrated to scratch-www, but for now there's no simple way, sorry.

**Comment by micahlt** [comment]
@RedGuy12 Take a look at [ScratchDB](https://scratchdb.lefty.one/), a third-party API wrapper that does have follower counts.
