### ISSUE TITLE
Add endpoints for personalized homepage projects

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/scratch-api-unofficial-docs#58]
Defined [here](https://github.com/LLK/scratch-www/blob/d5e51d2f18e6e680aa30775975daa4efd610df82/src/redux/splash.js#L127), [here](https://github.com/LLK/scratch-www/blob/d5e51d2f18e6e680aa30775975daa4efd610df82/src/redux/splash.js#L153), and [here](https://github.com/LLK/scratch-www/blob/d5e51d2f18e6e680aa30775975daa4efd610df82/src/redux/splash.js#L179), these (presumably) return project objects which are used to display thumbnails in the personalized homepage rows "Projects Loved by Scratchers I'm Following", etc. They replace the proxy endpoint `/proxy/users/<id>/featured`, which seems to be unused/gone now.

**Comment by micahlt** [comment]
The merging of #57 should resolve this issue.
