### ISSUE TITLE
Signature API

### ISSUE THREAD

**Issue by RedGuy12** [towerofnix/scratch-api-unofficial-docs#61]
Any way I can edit my form signature with the API?

**Comment by towerofnix** [comment]
Yep! Disclaimer: I haven't tested this, just sharing what I've gathered from inspecting the request the browser sends when changing a signature.

Send a POST request to `https://scratch.mit.edu/discuss/settings/<yourUsername>/`. It should contain your `scratchsessionsid` cookie. It will be a `content-type: application/x-www-form-urlencoded` request (i.e. a normal HTML form-style POST request), and as form data you should set the `signature` parameter to the string you want to set the new signature to. You may also have to set a `csrfmiddlewaretoken` to your [Scratch CSRF token](https://gist.github.com/towerofnix/cd5c0771446dc0ba81355fccc70ed1ea#csrf-tokens), but it's possible it will also work if set to a normal string (e.g. `a`) or not specified at all (haven't tested).

**Comment by RedGuy12** [comment]
Ok! Any way to view it?

**Comment by towerofnix** [comment]
Not that I know of, sorry. There's an API for getting the source content of *posts* but that doesn't include the signature (it's used for quoting), and I'm not sure if there's one for the signature itself.

If you have access to the request for changing the signature (i.e. are logged in as that user/have the session ID), you can totally fetch the HTML page and parse that, though -- i.e, same URL, just a GET request whose HTML contents you will have to parse. `id_signature` is the ID of the `<textarea>` you're looking for!

**Comment by RedGuy12** [comment]
Ok.

What's the first API you mentioned, the one for posts? I was using ScratchDB, but that doesn't count edits, so maybe this one would be better.

Paul Reid


________________________________

**Comment by RedGuy12** [comment]
Nvm, I found it. It's https://scratch.mit.edu/discuss/post/ID/source

Paul Reid
