### ISSUE TITLE
"/Comments" is deprecated

### ISSUE THREAD

**Issue by qwertykid** [towerofnix/scratch-api-unofficial-docs#73]
all endpoints at `/Comments` seem to not work.
Theres a diffrent endpoint at `/users/USERNAME/projects/PROJECT_ID/comments`
I hope this helps.

**Comment by towerofnix** [comment]
Thanks, I've addressed the updated endpoints now. Have a look at the links here: https://towerofnix.github.io/scratch-api-unofficial-docs/api/comments.html
