### ISSUE TITLE
Limit changed from 40 to 20

### ISSUE THREAD

**Issue by gjschaap0x** [towerofnix/scratch-api-unofficial-docs#74]
If I perform a GET request to https://api.scratch.mit.edu/users/MrMedra/projects , I receive a list with only 20 items, while the documentation says the limit is 40, even though the user has over 100 projects.

**Comment by towerofnix** [comment]
Thanks - I think this is a misstatement on the documentation's part. It says "[Limited](https://github.com/towerofnix/scratch-api-unofficial-docs/blob/main/etc/limits_and_offsets.md) to 40 results per request," which is true, but it doesn't mention that the default is 20 (like other sections).

You can get back 40 projects by adding `?limit=40` - anything about 40 is a `BadRequest` error.
