### ISSUE TITLE
How can I authenticate scratch users for my web app?

### ISSUE THREAD

**Issue by Theooolone** [towerofnix/scratch-api-unofficial-docs#77]
I don't know how to message people on GitHub so I'm posting this here because you all seem to know what you're talking about, sorry if this isn't the correct place to ask this.

I read [your authentication.md page](https://github.com/towerofnix/scratch-api-unofficial-docs/blob/main/etc/authentication.md) and I'd like to know how I would get a user token when provided with the username and password. Is there a way to do this in JS (or other client-side languages that run in a browser)? I wish for all the code to run client-side without my webserver handling any passwords or tokens for security reasons.

If it's possible to get the user token from https://scratch.mit.edu/session/ without a need for logging in, that would be much better. But i assume that's not possible due to the security implications.

**Comment by micahlt** [comment]
It's not possible.  You'll encounter Cross-Origin Resource Sharing (CORS) errors if you try to do so.  The only way you can make requests to the auth API is via a CORS proxy or with your own server/serverless functions.

**Comment by towerofnix** [comment]
Moreover, writing and sharing a web app that takes a Scratcher's username and password (even if your own code is well-meaning) is generally considered a really bad sign — that's what causes phishing. Scratchers have no idea if you're going to steal and keep track of their password, after you enter it! Plus, if you use a CORS proxy, *you* have no idea that the *proxy* isn't logging (and stealing) the requests you make with it. If you manage someone's passwords or even session IDs, not only do you have to take due responsibility for your own code, but the whole system and server they're on, or else you're risking them losing it. And the *visitors* to your site pretty much just have to blindly trust that you're taking their security as carefully as possible, *and* aren't out to steal their passwords in the first place.

Have a look at this somewhat classic project by Lightnin: [Gobo Gets Phished](https://scratch.mit.edu/projects/2778121)
