### ISSUE TITLE
Use the repository

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/scratch-api-unofficial-docs#9]
I know we already switched (#2) to using the wiki, but nobody knows when we update the docs if it's in the wiki, so I say use the repository.

**Comment by liam4** [comment]
read: "we're going to use the repository as our main method of information storing"

**Comment by GarethPW** [comment]
If you like, I could just set up a page on the official wiki... How about http://wiki.scratch.mit.edu/wiki/User:Gaza101/API_Docs whilst I'm writing it?

**Comment by Arinerron** [comment]
@GarethPW That'd be great. I'm trying to find some solid api docs, but they seem to be scattered across the internet and it is irratating to have to go though my large list of sites with API docs to have to find a certain request I need... There is also a lot of missing AI l API documentation though. I hope this becomes the home for *all* of the API in the future... :)

**Comment by liam4** [comment]
@GarethPW Sounds cool!

**Comment by GarethPW** [comment]
@Arinerron @liam4 I'll be including as much information as I can (including uses of site-api and api.scratch.mit.edu if there are no known spirit-staging alternatives). If you guys have any links to information regarding the API, please don't hesitate to send me them!

**Comment by liam4** [comment]
AFAIK api-staging is a mirror (possibly more recently updated) of api.

**Comment by GarethPW** [comment]
**[You're welcome.](http://wiki.scratch.mit.edu/wiki/Scratch_API_(2.0))**

**Comment by towerofnix** [comment]
Considered complete. The wiki is disabled.
